version: '3'
services:
  proxy:
    image: localhost:5000/my-website/proxy:1.0.0
    build: ./proxy
    ports:
      - '80:3000'
  frontend:
    image: localhost:5000/my-website/frontend:1.0.0
    build: ./frontend
  api:
    image: localhost:5000/my-website/api:1.0.0
    build: ./api
