version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - '3000:3000'
  frontend:
    build: ./frontend
    volumes:
      - './frontend/src:/frontend/src'
  api:
    build: ./api
    volumes:
      - './api:/app'
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1

