version: '3'
services:
  proxy:
    image: localhost:5000/my-website/proxy:${WEBSITE_VERSION}
    build: ./proxy
    ports:
      - '80:3000'
  frontend:
    image: localhost:5000/my-website/frontend:${WEBSITE_VERSION}
    build: ./frontend
  api:
    image: localhost:5000/my-website/api:${WEBSITE_VERSION}
    build: ./api
